// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/auctioneer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidResponce_Ack int32

const (
	BidResponce_SUCCESS   BidResponce_Ack = 0
	BidResponce_FAIL      BidResponce_Ack = 1
	BidResponce_EXCEPTION BidResponce_Ack = 2
)

// Enum value maps for BidResponce_Ack.
var (
	BidResponce_Ack_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "EXCEPTION",
	}
	BidResponce_Ack_value = map[string]int32{
		"SUCCESS":   0,
		"FAIL":      1,
		"EXCEPTION": 2,
	}
)

func (x BidResponce_Ack) Enum() *BidResponce_Ack {
	p := new(BidResponce_Ack)
	*p = x
	return p
}

func (x BidResponce_Ack) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidResponce_Ack) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auctioneer_proto_enumTypes[0].Descriptor()
}

func (BidResponce_Ack) Type() protoreflect.EnumType {
	return &file_proto_auctioneer_proto_enumTypes[0]
}

func (x BidResponce_Ack) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidResponce_Ack.Descriptor instead.
func (BidResponce_Ack) EnumDescriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{5, 0}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LamportClock  int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	PortToRemove  string                 `protobuf:"bytes,2,opt,name=PortToRemove,proto3" json:"PortToRemove,omitempty"`
	PortToAdd     string                 `protobuf:"bytes,3,opt,name=PortToAdd,proto3" json:"PortToAdd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *RemoveRequest) GetPortToRemove() string {
	if x != nil {
		return x.PortToRemove
	}
	return ""
}

func (x *RemoveRequest) GetPortToAdd() string {
	if x != nil {
		return x.PortToAdd
	}
	return ""
}

type RemoveResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LamportClock  int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponce) Reset() {
	*x = RemoveResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponce) ProtoMessage() {}

func (x *RemoveResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponce.ProtoReflect.Descriptor instead.
func (*RemoveResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LamportClock   int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	KnownAddresses []string               `protobuf:"bytes,2,rep,name=KnownAddresses,proto3" json:"KnownAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *JoinRequest) GetKnownAddresses() []string {
	if x != nil {
		return x.KnownAddresses
	}
	return nil
}

type JoinResponce struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LamportClock   int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	KnownAddresses []string               `protobuf:"bytes,2,rep,name=KnownAddresses,proto3" json:"KnownAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinResponce) Reset() {
	*x = JoinResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponce) ProtoMessage() {}

func (x *JoinResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponce.ProtoReflect.Descriptor instead.
func (*JoinResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{3}
}

func (x *JoinResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *JoinResponce) GetKnownAddresses() []string {
	if x != nil {
		return x.KnownAddresses
	}
	return nil
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LamportClock  int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	Bid           int64                  `protobuf:"varint,2,opt,name=Bid,proto3" json:"Bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{4}
}

func (x *BidRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *BidRequest) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

type BidResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LamportClock  int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	SuccesfulBid  BidResponce_Ack        `protobuf:"varint,2,opt,name=SuccesfulBid,proto3,enum=auctioneer.BidResponce_Ack" json:"SuccesfulBid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponce) Reset() {
	*x = BidResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponce) ProtoMessage() {}

func (x *BidResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponce.ProtoReflect.Descriptor instead.
func (*BidResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{5}
}

func (x *BidResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *BidResponce) GetSuccesfulBid() BidResponce_Ack {
	if x != nil {
		return x.SuccesfulBid
	}
	return BidResponce_SUCCESS
}

type ResultResponce struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LamportClock     int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	IsAuctionRunning bool                   `protobuf:"varint,2,opt,name=IsAuctionRunning,proto3" json:"IsAuctionRunning,omitempty"`
	Winner           string                 `protobuf:"bytes,3,opt,name=Winner,proto3" json:"Winner,omitempty"`
	TopBid           int64                  `protobuf:"varint,4,opt,name=TopBid,proto3" json:"TopBid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResultResponce) Reset() {
	*x = ResultResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponce) ProtoMessage() {}

func (x *ResultResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponce.ProtoReflect.Descriptor instead.
func (*ResultResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{6}
}

func (x *ResultResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *ResultResponce) GetIsAuctionRunning() bool {
	if x != nil {
		return x.IsAuctionRunning
	}
	return false
}

func (x *ResultResponce) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *ResultResponce) GetTopBid() int64 {
	if x != nil {
		return x.TopBid
	}
	return 0
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LamportClock  int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{7}
}

func (x *ResultRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_auctioneer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{8}
}

var File_proto_auctioneer_proto protoreflect.FileDescriptor

const file_proto_auctioneer_proto_rawDesc = "" +
	"\n" +
	"\x16proto/auctioneer.proto\x12\n" +
	"auctioneer\"u\n" +
	"\rRemoveRequest\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12\"\n" +
	"\fPortToRemove\x18\x02 \x01(\tR\fPortToRemove\x12\x1c\n" +
	"\tPortToAdd\x18\x03 \x01(\tR\tPortToAdd\"4\n" +
	"\x0eRemoveResponce\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\"Y\n" +
	"\vJoinRequest\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12&\n" +
	"\x0eKnownAddresses\x18\x02 \x03(\tR\x0eKnownAddresses\"Z\n" +
	"\fJoinResponce\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12&\n" +
	"\x0eKnownAddresses\x18\x02 \x03(\tR\x0eKnownAddresses\"B\n" +
	"\n" +
	"BidRequest\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12\x10\n" +
	"\x03Bid\x18\x02 \x01(\x03R\x03Bid\"\x9f\x01\n" +
	"\vBidResponce\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12?\n" +
	"\fSuccesfulBid\x18\x02 \x01(\x0e2\x1b.auctioneer.BidResponce.AckR\fSuccesfulBid\"+\n" +
	"\x03Ack\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02\"\x90\x01\n" +
	"\x0eResultResponce\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12*\n" +
	"\x10IsAuctionRunning\x18\x02 \x01(\bR\x10IsAuctionRunning\x12\x16\n" +
	"\x06Winner\x18\x03 \x01(\tR\x06Winner\x12\x16\n" +
	"\x06TopBid\x18\x04 \x01(\x03R\x06TopBid\"3\n" +
	"\rResultRequest\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\"\a\n" +
	"\x05Empty2\x9a\x02\n" +
	"\n" +
	"auctioneer\x12<\n" +
	"\aSendBid\x12\x16.auctioneer.BidRequest\x1a\x17.auctioneer.BidResponce\"\x00\x12B\n" +
	"\aResults\x12\x19.auctioneer.ResultRequest\x1a\x1a.auctioneer.ResultResponce\"\x00\x12?\n" +
	"\bJoinMesh\x12\x17.auctioneer.JoinRequest\x1a\x18.auctioneer.JoinResponce\"\x00\x12I\n" +
	"\x0eRemoveFromMesh\x12\x19.auctioneer.RemoveRequest\x1a\x1a.auctioneer.RemoveResponce\"\x00B\"Z distributed-Auction-System/protob\x06proto3"

var (
	file_proto_auctioneer_proto_rawDescOnce sync.Once
	file_proto_auctioneer_proto_rawDescData []byte
)

func file_proto_auctioneer_proto_rawDescGZIP() []byte {
	file_proto_auctioneer_proto_rawDescOnce.Do(func() {
		file_proto_auctioneer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auctioneer_proto_rawDesc), len(file_proto_auctioneer_proto_rawDesc)))
	})
	return file_proto_auctioneer_proto_rawDescData
}

var file_proto_auctioneer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_auctioneer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_auctioneer_proto_goTypes = []any{
	(BidResponce_Ack)(0),   // 0: auctioneer.BidResponce.Ack
	(*RemoveRequest)(nil),  // 1: auctioneer.RemoveRequest
	(*RemoveResponce)(nil), // 2: auctioneer.RemoveResponce
	(*JoinRequest)(nil),    // 3: auctioneer.JoinRequest
	(*JoinResponce)(nil),   // 4: auctioneer.JoinResponce
	(*BidRequest)(nil),     // 5: auctioneer.BidRequest
	(*BidResponce)(nil),    // 6: auctioneer.BidResponce
	(*ResultResponce)(nil), // 7: auctioneer.ResultResponce
	(*ResultRequest)(nil),  // 8: auctioneer.ResultRequest
	(*Empty)(nil),          // 9: auctioneer.Empty
}
var file_proto_auctioneer_proto_depIdxs = []int32{
	0, // 0: auctioneer.BidResponce.SuccesfulBid:type_name -> auctioneer.BidResponce.Ack
	5, // 1: auctioneer.auctioneer.SendBid:input_type -> auctioneer.BidRequest
	8, // 2: auctioneer.auctioneer.Results:input_type -> auctioneer.ResultRequest
	3, // 3: auctioneer.auctioneer.JoinMesh:input_type -> auctioneer.JoinRequest
	1, // 4: auctioneer.auctioneer.RemoveFromMesh:input_type -> auctioneer.RemoveRequest
	6, // 5: auctioneer.auctioneer.SendBid:output_type -> auctioneer.BidResponce
	7, // 6: auctioneer.auctioneer.Results:output_type -> auctioneer.ResultResponce
	4, // 7: auctioneer.auctioneer.JoinMesh:output_type -> auctioneer.JoinResponce
	2, // 8: auctioneer.auctioneer.RemoveFromMesh:output_type -> auctioneer.RemoveResponce
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_auctioneer_proto_init() }
func file_proto_auctioneer_proto_init() {
	if File_proto_auctioneer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auctioneer_proto_rawDesc), len(file_proto_auctioneer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auctioneer_proto_goTypes,
		DependencyIndexes: file_proto_auctioneer_proto_depIdxs,
		EnumInfos:         file_proto_auctioneer_proto_enumTypes,
		MessageInfos:      file_proto_auctioneer_proto_msgTypes,
	}.Build()
	File_proto_auctioneer_proto = out.File
	file_proto_auctioneer_proto_goTypes = nil
	file_proto_auctioneer_proto_depIdxs = nil
}
