// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/peer2peer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Peer2Peer_SendMessage_FullMethodName = "/peer2peer.Peer2Peer/SendMessage"
)

// Peer2PeerClient is the client API for Peer2Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Peer2PeerClient interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponce, error)
}

type peer2PeerClient struct {
	cc grpc.ClientConnInterface
}

func NewPeer2PeerClient(cc grpc.ClientConnInterface) Peer2PeerClient {
	return &peer2PeerClient{cc}
}

func (c *peer2PeerClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponce)
	err := c.cc.Invoke(ctx, Peer2Peer_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Peer2PeerServer is the server API for Peer2Peer service.
// All implementations must embed UnimplementedPeer2PeerServer
// for forward compatibility.
type Peer2PeerServer interface {
	SendMessage(context.Context, *MessageRequest) (*MessageResponce, error)
	mustEmbedUnimplementedPeer2PeerServer()
}

// UnimplementedPeer2PeerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeer2PeerServer struct{}

func (UnimplementedPeer2PeerServer) SendMessage(context.Context, *MessageRequest) (*MessageResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPeer2PeerServer) mustEmbedUnimplementedPeer2PeerServer() {}
func (UnimplementedPeer2PeerServer) testEmbeddedByValue()                   {}

// UnsafePeer2PeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Peer2PeerServer will
// result in compilation errors.
type UnsafePeer2PeerServer interface {
	mustEmbedUnimplementedPeer2PeerServer()
}

func RegisterPeer2PeerServer(s grpc.ServiceRegistrar, srv Peer2PeerServer) {
	// If the following call pancis, it indicates UnimplementedPeer2PeerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Peer2Peer_ServiceDesc, srv)
}

func _Peer2Peer_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Peer2PeerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peer2Peer_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Peer2PeerServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Peer2Peer_ServiceDesc is the grpc.ServiceDesc for Peer2Peer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Peer2Peer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peer2peer.Peer2Peer",
	HandlerType: (*Peer2PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Peer2Peer_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/peer2peer.proto",
}
