// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidAcknowledgement_Status int32

const (
	BidAcknowledgement_Fail    BidAcknowledgement_Status = 0
	BidAcknowledgement_Success BidAcknowledgement_Status = 1
)

// Enum value maps for BidAcknowledgement_Status.
var (
	BidAcknowledgement_Status_name = map[int32]string{
		0: "Fail",
		1: "Success",
	}
	BidAcknowledgement_Status_value = map[string]int32{
		"Fail":    0,
		"Success": 1,
	}
)

func (x BidAcknowledgement_Status) Enum() *BidAcknowledgement_Status {
	p := new(BidAcknowledgement_Status)
	*p = x
	return p
}

func (x BidAcknowledgement_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidAcknowledgement_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (BidAcknowledgement_Status) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x BidAcknowledgement_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidAcknowledgement_Status.Descriptor instead.
func (BidAcknowledgement_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1, 0}
}

type SellAcknowledgement_Status int32

const (
	SellAcknowledgement_FAIL    SellAcknowledgement_Status = 0
	SellAcknowledgement_Success SellAcknowledgement_Status = 1
)

// Enum value maps for SellAcknowledgement_Status.
var (
	SellAcknowledgement_Status_name = map[int32]string{
		0: "FAIL",
		1: "Success",
	}
	SellAcknowledgement_Status_value = map[string]int32{
		"FAIL":    0,
		"Success": 1,
	}
)

func (x SellAcknowledgement_Status) Enum() *SellAcknowledgement_Status {
	p := new(SellAcknowledgement_Status)
	*p = x
	return p
}

func (x SellAcknowledgement_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SellAcknowledgement_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[1].Descriptor()
}

func (SellAcknowledgement_Status) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[1]
}

func (x SellAcknowledgement_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SellAcknowledgement_Status.Descriptor instead.
func (SellAcknowledgement_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2, 0}
}

type Outcome_AuctionStatus int32

const (
	Outcome_Running  Outcome_AuctionStatus = 0
	Outcome_Finished Outcome_AuctionStatus = 1
)

// Enum value maps for Outcome_AuctionStatus.
var (
	Outcome_AuctionStatus_name = map[int32]string{
		0: "Running",
		1: "Finished",
	}
	Outcome_AuctionStatus_value = map[string]int32{
		"Running":  0,
		"Finished": 1,
	}
)

func (x Outcome_AuctionStatus) Enum() *Outcome_AuctionStatus {
	p := new(Outcome_AuctionStatus)
	*p = x
	return p
}

func (x Outcome_AuctionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome_AuctionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[2].Descriptor()
}

func (Outcome_AuctionStatus) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[2]
}

func (x Outcome_AuctionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome_AuctionStatus.Descriptor instead.
func (Outcome_AuctionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3, 0}
}

// processID: The ID of the process sending the bid
type BidInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionID     int32                  `protobuf:"varint,1,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	ProcessID     int32                  `protobuf:"varint,2,opt,name=processID,proto3" json:"processID,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidInfo) Reset() {
	*x = BidInfo{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidInfo) ProtoMessage() {}

func (x *BidInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidInfo.ProtoReflect.Descriptor instead.
func (*BidInfo) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidInfo) GetAuctionID() int32 {
	if x != nil {
		return x.AuctionID
	}
	return 0
}

func (x *BidInfo) GetProcessID() int32 {
	if x != nil {
		return x.ProcessID
	}
	return 0
}

func (x *BidInfo) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// *
// Indicates whether the bid sent from the client was successful or not. Returns Fail when client underbid
type BidAcknowledgement struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        BidAcknowledgement_Status `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.BidAcknowledgement_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAcknowledgement) Reset() {
	*x = BidAcknowledgement{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAcknowledgement) ProtoMessage() {}

func (x *BidAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAcknowledgement.ProtoReflect.Descriptor instead.
func (*BidAcknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *BidAcknowledgement) GetStatus() BidAcknowledgement_Status {
	if x != nil {
		return x.Status
	}
	return BidAcknowledgement_Fail
}

type SellAcknowledgement struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        SellAcknowledgement_Status `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.SellAcknowledgement_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellAcknowledgement) Reset() {
	*x = SellAcknowledgement{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellAcknowledgement) ProtoMessage() {}

func (x *SellAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellAcknowledgement.ProtoReflect.Descriptor instead.
func (*SellAcknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *SellAcknowledgement) GetStatus() SellAcknowledgement_Status {
	if x != nil {
		return x.Status
	}
	return SellAcknowledgement_FAIL
}

// *
// AuctionStatus: Running = Clients can still bid | Finished = Auction is over and a winner has been decided
// winnerID: The processID of the current winner of the auction. When auction is Finished, this will be the winner
// currentBid: The current highest bid for this auction
// auctionID: The ID of this auction
type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Outcome_AuctionStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.Outcome_AuctionStatus" json:"status,omitempty"`
	WinnerID      int32                  `protobuf:"varint,2,opt,name=winnerID,proto3" json:"winnerID,omitempty"`
	CurrentBid    int32                  `protobuf:"varint,3,opt,name=currentBid,proto3" json:"currentBid,omitempty"`
	AuctionID     int32                  `protobuf:"varint,4,opt,name=auctionID,proto3" json:"auctionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Outcome) GetStatus() Outcome_AuctionStatus {
	if x != nil {
		return x.Status
	}
	return Outcome_Running
}

func (x *Outcome) GetWinnerID() int32 {
	if x != nil {
		return x.WinnerID
	}
	return 0
}

func (x *Outcome) GetCurrentBid() int32 {
	if x != nil {
		return x.CurrentBid
	}
	return 0
}

func (x *Outcome) GetAuctionID() int32 {
	if x != nil {
		return x.AuctionID
	}
	return 0
}

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Timeframe     int32                  `protobuf:"varint,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Auction) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Auction) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *Auction) GetTimeframe() int32 {
	if x != nil {
		return x.Timeframe
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\x12\x04grpc\"]\n" +
	"\aBidInfo\x12\x1c\n" +
	"\tauctionID\x18\x01 \x01(\x05R\tauctionID\x12\x1c\n" +
	"\tprocessID\x18\x02 \x01(\x05R\tprocessID\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"n\n" +
	"\x12BidAcknowledgement\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.grpc.BidAcknowledgement.StatusR\x06status\"\x1f\n" +
	"\x06Status\x12\b\n" +
	"\x04Fail\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\"p\n" +
	"\x13SellAcknowledgement\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .grpc.SellAcknowledgement.StatusR\x06status\"\x1f\n" +
	"\x06Status\x12\b\n" +
	"\x04FAIL\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\"\xc4\x01\n" +
	"\aOutcome\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.grpc.Outcome.AuctionStatusR\x06status\x12\x1a\n" +
	"\bwinnerID\x18\x02 \x01(\x05R\bwinnerID\x12\x1e\n" +
	"\n" +
	"currentBid\x18\x03 \x01(\x05R\n" +
	"currentBid\x12\x1c\n" +
	"\tauctionID\x18\x04 \x01(\x05R\tauctionID\"*\n" +
	"\rAuctionStatus\x12\v\n" +
	"\aRunning\x10\x00\x12\f\n" +
	"\bFinished\x10\x01\"Q\n" +
	"\aAuction\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\x05R\ttimeframe\"\a\n" +
	"\x05Empty2\xce\x01\n" +
	"\fAuctionHouse\x120\n" +
	"\x03Bid\x12\r.grpc.BidInfo\x1a\x18.grpc.BidAcknowledgement\"\x00\x122\n" +
	"\x04Sell\x12\r.grpc.Auction\x1a\x19.grpc.SellAcknowledgement\"\x00\x12&\n" +
	"\x06Result\x12\r.grpc.Outcome\x1a\v.grpc.Empty\"\x00\x120\n" +
	"\x0eAuctionOutcome\x12\r.grpc.Auction\x1a\r.grpc.Outcome\"\x00B\x1aZ\x18Auction-House/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proto_goTypes = []any{
	(BidAcknowledgement_Status)(0),  // 0: grpc.BidAcknowledgement.Status
	(SellAcknowledgement_Status)(0), // 1: grpc.SellAcknowledgement.Status
	(Outcome_AuctionStatus)(0),      // 2: grpc.Outcome.AuctionStatus
	(*BidInfo)(nil),                 // 3: grpc.BidInfo
	(*BidAcknowledgement)(nil),      // 4: grpc.BidAcknowledgement
	(*SellAcknowledgement)(nil),     // 5: grpc.SellAcknowledgement
	(*Outcome)(nil),                 // 6: grpc.Outcome
	(*Auction)(nil),                 // 7: grpc.Auction
	(*Empty)(nil),                   // 8: grpc.Empty
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: grpc.BidAcknowledgement.status:type_name -> grpc.BidAcknowledgement.Status
	1, // 1: grpc.SellAcknowledgement.status:type_name -> grpc.SellAcknowledgement.Status
	2, // 2: grpc.Outcome.status:type_name -> grpc.Outcome.AuctionStatus
	3, // 3: grpc.AuctionHouse.Bid:input_type -> grpc.BidInfo
	7, // 4: grpc.AuctionHouse.Sell:input_type -> grpc.Auction
	6, // 5: grpc.AuctionHouse.Result:input_type -> grpc.Outcome
	7, // 6: grpc.AuctionHouse.AuctionOutcome:input_type -> grpc.Auction
	4, // 7: grpc.AuctionHouse.Bid:output_type -> grpc.BidAcknowledgement
	5, // 8: grpc.AuctionHouse.Sell:output_type -> grpc.SellAcknowledgement
	8, // 9: grpc.AuctionHouse.Result:output_type -> grpc.Empty
	6, // 10: grpc.AuctionHouse.AuctionOutcome:output_type -> grpc.Outcome
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
