// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage_MessageType int32

const (
	ChatMessage_REGULAR ChatMessage_MessageType = 0
	ChatMessage_JOIN    ChatMessage_MessageType = 1
	ChatMessage_LEAVE   ChatMessage_MessageType = 2
)

// Enum value maps for ChatMessage_MessageType.
var (
	ChatMessage_MessageType_name = map[int32]string{
		0: "REGULAR",
		1: "JOIN",
		2: "LEAVE",
	}
	ChatMessage_MessageType_value = map[string]int32{
		"REGULAR": 0,
		"JOIN":    1,
		"LEAVE":   2,
	}
)

func (x ChatMessage_MessageType) Enum() *ChatMessage_MessageType {
	p := new(ChatMessage_MessageType)
	*p = x
	return p
}

func (x ChatMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_proto_enumTypes[0].Descriptor()
}

func (ChatMessage_MessageType) Type() protoreflect.EnumType {
	return &file_grpc_proto_proto_enumTypes[0]
}

func (x ChatMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessage_MessageType.Descriptor instead.
func (ChatMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{3, 0}
}

type TimeOld struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time2         int64                  `protobuf:"varint,1,opt,name=time2,proto3" json:"time2,omitempty"`
	Time3         int64                  `protobuf:"varint,2,opt,name=time3,proto3" json:"time3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeOld) Reset() {
	*x = TimeOld{}
	mi := &file_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeOld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeOld) ProtoMessage() {}

func (x *TimeOld) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeOld.ProtoReflect.Descriptor instead.
func (*TimeOld) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *TimeOld) GetTime2() int64 {
	if x != nil {
		return x.Time2
	}
	return 0
}

func (x *TimeOld) GetTime3() int64 {
	if x != nil {
		return x.Time3
	}
	return 0
}

type Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Time) Reset() {
	*x = Time{}
	mi := &file_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Time) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type VectorClocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clocks        map[string]int64       `protobuf:"bytes,1,rep,name=clocks,proto3" json:"clocks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	VectorClocks  *VectorClocks          `protobuf:"bytes,2,opt,name=vector_clocks,json=vectorClocks,proto3" json:"vector_clocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClocks) Reset() {
	*x = VectorClocks{}
	mi := &file_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClocks) ProtoMessage() {}

func (x *VectorClocks) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClocks.ProtoReflect.Descriptor instead.
func (*VectorClocks) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *VectorClocks) GetClocks() map[string]int64 {
	if x != nil {
		return x.Clocks
	}
	return nil
}

func (x *VectorClocks) GetVectorClocks() *VectorClocks {
	if x != nil {
		return x.VectorClocks
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Message       string                  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	User          string                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Type          ChatMessage_MessageType `protobuf:"varint,3,opt,name=type,proto3,enum=ChatMessage_MessageType" json:"type,omitempty"`
	VectorClocks  *VectorClocks           `protobuf:"bytes,4,opt,name=vector_clocks,json=vectorClocks,proto3" json:"vector_clocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessage) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ChatMessage) GetType() ChatMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return ChatMessage_REGULAR
}

func (x *ChatMessage) GetVectorClocks() *VectorClocks {
	if x != nil {
		return x.VectorClocks
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	VectorClocks  *VectorClocks          `protobuf:"bytes,2,opt,name=vector_clocks,json=vectorClocks,proto3" json:"vector_clocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *JoinRequest) GetVectorClocks() *VectorClocks {
	if x != nil {
		return x.VectorClocks
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClocks  *VectorClocks          `protobuf:"bytes,3,opt,name=vector_clocks,json=vectorClocks,proto3" json:"vector_clocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_grpc_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetVectorClocks() *VectorClocks {
	if x != nil {
		return x.VectorClocks
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_proto_rawDescGZIP(), []int{6}
}

var File_grpc_proto_proto protoreflect.FileDescriptor

const file_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x10grpc/proto.proto\"5\n" +
	"\aTimeOld\x12\x14\n" +
	"\x05time2\x18\x01 \x01(\x03R\x05time2\x12\x14\n" +
	"\x05time3\x18\x02 \x01(\x03R\x05time3\"\x1a\n" +
	"\x04Time\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"\xb0\x01\n" +
	"\fVectorClocks\x121\n" +
	"\x06clocks\x18\x01 \x03(\v2\x19.VectorClocks.ClocksEntryR\x06clocks\x122\n" +
	"\rvector_clocks\x18\x02 \x01(\v2\r.VectorClocksR\fvectorClocks\x1a9\n" +
	"\vClocksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xce\x01\n" +
	"\vChatMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.ChatMessage.MessageTypeR\x04type\x122\n" +
	"\rvector_clocks\x18\x04 \x01(\v2\r.VectorClocksR\fvectorClocks\"/\n" +
	"\vMessageType\x12\v\n" +
	"\aREGULAR\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x02\"U\n" +
	"\vJoinRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x122\n" +
	"\rvector_clocks\x18\x02 \x01(\v2\r.VectorClocksR\fvectorClocks\"v\n" +
	"\x12SendMessageRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\rvector_clocks\x18\x03 \x01(\v2\r.VectorClocksR\fvectorClocks\"\a\n" +
	"\x05Empty2\x82\x01\n" +
	"\bChitChat\x12\x1b\n" +
	"\agetTime\x12\x06.Empty\x1a\b.TimeOld\x12.\n" +
	"\x0ereceiveMessage\x12\f.JoinRequest\x1a\f.ChatMessage0\x01\x12)\n" +
	"\vsendMessage\x12\x13.SendMessageRequest\x1a\x05.TimeB\x1aZ\x18/go/chit-chat/grpc/protob\x06proto3"

var (
	file_grpc_proto_proto_rawDescOnce sync.Once
	file_grpc_proto_proto_rawDescData []byte
)

func file_grpc_proto_proto_rawDescGZIP() []byte {
	file_grpc_proto_proto_rawDescOnce.Do(func() {
		file_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)))
	})
	return file_grpc_proto_proto_rawDescData
}

var file_grpc_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_proto_proto_goTypes = []any{
	(ChatMessage_MessageType)(0), // 0: ChatMessage.MessageType
	(*TimeOld)(nil),              // 1: TimeOld
	(*Time)(nil),                 // 2: Time
	(*VectorClocks)(nil),         // 3: VectorClocks
	(*ChatMessage)(nil),          // 4: ChatMessage
	(*JoinRequest)(nil),          // 5: JoinRequest
	(*SendMessageRequest)(nil),   // 6: SendMessageRequest
	(*Empty)(nil),                // 7: Empty
	nil,                          // 8: VectorClocks.ClocksEntry
}
var file_grpc_proto_proto_depIdxs = []int32{
	8, // 0: VectorClocks.clocks:type_name -> VectorClocks.ClocksEntry
	3, // 1: VectorClocks.vector_clocks:type_name -> VectorClocks
	0, // 2: ChatMessage.type:type_name -> ChatMessage.MessageType
	3, // 3: ChatMessage.vector_clocks:type_name -> VectorClocks
	3, // 4: JoinRequest.vector_clocks:type_name -> VectorClocks
	3, // 5: SendMessageRequest.vector_clocks:type_name -> VectorClocks
	7, // 6: ChitChat.getTime:input_type -> Empty
	5, // 7: ChitChat.receiveMessage:input_type -> JoinRequest
	6, // 8: ChitChat.sendMessage:input_type -> SendMessageRequest
	1, // 9: ChitChat.getTime:output_type -> TimeOld
	4, // 10: ChitChat.receiveMessage:output_type -> ChatMessage
	2, // 11: ChitChat.sendMessage:output_type -> Time
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_grpc_proto_proto_init() }
func file_grpc_proto_proto_init() {
	if File_grpc_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_proto_rawDesc), len(file_grpc_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_proto_goTypes,
		DependencyIndexes: file_grpc_proto_proto_depIdxs,
		EnumInfos:         file_grpc_proto_proto_enumTypes,
		MessageInfos:      file_grpc_proto_proto_msgTypes,
	}.Build()
	File_grpc_proto_proto = out.File
	file_grpc_proto_proto_goTypes = nil
	file_grpc_proto_proto_depIdxs = nil
}
