// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/auctioneer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LamportClock   int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	KnownAddresses []string               `protobuf:"bytes,2,rep,name=KnownAddresses,proto3" json:"KnownAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *JoinRequest) GetKnownAddresses() []string {
	if x != nil {
		return x.KnownAddresses
	}
	return nil
}

type JoinResponce struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LamportClock   int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	KnownAddresses []string               `protobuf:"bytes,2,rep,name=KnownAddresses,proto3" json:"KnownAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinResponce) Reset() {
	*x = JoinResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponce) ProtoMessage() {}

func (x *JoinResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponce.ProtoReflect.Descriptor instead.
func (*JoinResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *JoinResponce) GetKnownAddresses() []string {
	if x != nil {
		return x.KnownAddresses
	}
	return nil
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           int64                  `protobuf:"varint,1,opt,name=Bid,proto3" json:"Bid,omitempty"`
	LamportClock  int64                  `protobuf:"varint,2,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{2}
}

func (x *BidRequest) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *BidRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type BidResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccesfulBid  bool                   `protobuf:"varint,1,opt,name=SuccesfulBid,proto3" json:"SuccesfulBid,omitempty"`
	LamportClock  int64                  `protobuf:"varint,2,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponce) Reset() {
	*x = BidResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponce) ProtoMessage() {}

func (x *BidResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponce.ProtoReflect.Descriptor instead.
func (*BidResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{3}
}

func (x *BidResponce) GetSuccesfulBid() bool {
	if x != nil {
		return x.SuccesfulBid
	}
	return false
}

func (x *BidResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type Outcome struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsAuctionRunning bool                   `protobuf:"varint,1,opt,name=IsAuctionRunning,proto3" json:"IsAuctionRunning,omitempty"`
	Winner           string                 `protobuf:"bytes,2,opt,name=Winner,proto3" json:"Winner,omitempty"`
	TopBid           int64                  `protobuf:"varint,3,opt,name=TopBid,proto3" json:"TopBid,omitempty"`
	LamportClock     int64                  `protobuf:"varint,4,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_proto_auctioneer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{4}
}

func (x *Outcome) GetIsAuctionRunning() bool {
	if x != nil {
		return x.IsAuctionRunning
	}
	return false
}

func (x *Outcome) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *Outcome) GetTopBid() int64 {
	if x != nil {
		return x.TopBid
	}
	return 0
}

func (x *Outcome) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type RemovePortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldAddress    string                 `protobuf:"bytes,1,opt,name=OldAddress,proto3" json:"OldAddress,omitempty"`
	LamportClock  int64                  `protobuf:"varint,2,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePortRequest) Reset() {
	*x = RemovePortRequest{}
	mi := &file_proto_auctioneer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePortRequest) ProtoMessage() {}

func (x *RemovePortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePortRequest.ProtoReflect.Descriptor instead.
func (*RemovePortRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePortRequest) GetOldAddress() string {
	if x != nil {
		return x.OldAddress
	}
	return ""
}

func (x *RemovePortRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type RemovePortResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LamportClock  int64                  `protobuf:"varint,1,opt,name=LamportClock,proto3" json:"LamportClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePortResponce) Reset() {
	*x = RemovePortResponce{}
	mi := &file_proto_auctioneer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePortResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePortResponce) ProtoMessage() {}

func (x *RemovePortResponce) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePortResponce.ProtoReflect.Descriptor instead.
func (*RemovePortResponce) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePortResponce) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_auctioneer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctioneer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_auctioneer_proto_rawDescGZIP(), []int{7}
}

var File_proto_auctioneer_proto protoreflect.FileDescriptor

const file_proto_auctioneer_proto_rawDesc = "" +
	"\n" +
	"\x16proto/auctioneer.proto\x12\n" +
	"auctioneer\"Y\n" +
	"\vJoinRequest\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12&\n" +
	"\x0eKnownAddresses\x18\x02 \x03(\tR\x0eKnownAddresses\"Z\n" +
	"\fJoinResponce\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\x12&\n" +
	"\x0eKnownAddresses\x18\x02 \x03(\tR\x0eKnownAddresses\"B\n" +
	"\n" +
	"BidRequest\x12\x10\n" +
	"\x03Bid\x18\x01 \x01(\x03R\x03Bid\x12\"\n" +
	"\fLamportClock\x18\x02 \x01(\x03R\fLamportClock\"U\n" +
	"\vBidResponce\x12\"\n" +
	"\fSuccesfulBid\x18\x01 \x01(\bR\fSuccesfulBid\x12\"\n" +
	"\fLamportClock\x18\x02 \x01(\x03R\fLamportClock\"\x89\x01\n" +
	"\aOutcome\x12*\n" +
	"\x10IsAuctionRunning\x18\x01 \x01(\bR\x10IsAuctionRunning\x12\x16\n" +
	"\x06Winner\x18\x02 \x01(\tR\x06Winner\x12\x16\n" +
	"\x06TopBid\x18\x03 \x01(\x03R\x06TopBid\x12\"\n" +
	"\fLamportClock\x18\x04 \x01(\x03R\fLamportClock\"W\n" +
	"\x11RemovePortRequest\x12\x1e\n" +
	"\n" +
	"OldAddress\x18\x01 \x01(\tR\n" +
	"OldAddress\x12\"\n" +
	"\fLamportClock\x18\x02 \x01(\x03R\fLamportClock\"8\n" +
	"\x12RemovePortResponce\x12\"\n" +
	"\fLamportClock\x18\x01 \x01(\x03R\fLamportClock\"\a\n" +
	"\x05Empty2\x8f\x02\n" +
	"\n" +
	"auctioneer\x12<\n" +
	"\aSendBid\x12\x16.auctioneer.BidRequest\x1a\x17.auctioneer.BidResponce\"\x00\x123\n" +
	"\aResults\x12\x11.auctioneer.Empty\x1a\x13.auctioneer.Outcome\"\x00\x12?\n" +
	"\bJoinMesh\x12\x17.auctioneer.JoinRequest\x1a\x18.auctioneer.JoinResponce\"\x00\x12M\n" +
	"\n" +
	"RemovePort\x12\x1d.auctioneer.RemovePortRequest\x1a\x1e.auctioneer.RemovePortResponce\"\x00B\"Z distributed-Auction-System/protob\x06proto3"

var (
	file_proto_auctioneer_proto_rawDescOnce sync.Once
	file_proto_auctioneer_proto_rawDescData []byte
)

func file_proto_auctioneer_proto_rawDescGZIP() []byte {
	file_proto_auctioneer_proto_rawDescOnce.Do(func() {
		file_proto_auctioneer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auctioneer_proto_rawDesc), len(file_proto_auctioneer_proto_rawDesc)))
	})
	return file_proto_auctioneer_proto_rawDescData
}

var file_proto_auctioneer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_auctioneer_proto_goTypes = []any{
	(*JoinRequest)(nil),        // 0: auctioneer.JoinRequest
	(*JoinResponce)(nil),       // 1: auctioneer.JoinResponce
	(*BidRequest)(nil),         // 2: auctioneer.BidRequest
	(*BidResponce)(nil),        // 3: auctioneer.BidResponce
	(*Outcome)(nil),            // 4: auctioneer.Outcome
	(*RemovePortRequest)(nil),  // 5: auctioneer.RemovePortRequest
	(*RemovePortResponce)(nil), // 6: auctioneer.RemovePortResponce
	(*Empty)(nil),              // 7: auctioneer.Empty
}
var file_proto_auctioneer_proto_depIdxs = []int32{
	2, // 0: auctioneer.auctioneer.SendBid:input_type -> auctioneer.BidRequest
	7, // 1: auctioneer.auctioneer.Results:input_type -> auctioneer.Empty
	0, // 2: auctioneer.auctioneer.JoinMesh:input_type -> auctioneer.JoinRequest
	5, // 3: auctioneer.auctioneer.RemovePort:input_type -> auctioneer.RemovePortRequest
	3, // 4: auctioneer.auctioneer.SendBid:output_type -> auctioneer.BidResponce
	4, // 5: auctioneer.auctioneer.Results:output_type -> auctioneer.Outcome
	1, // 6: auctioneer.auctioneer.JoinMesh:output_type -> auctioneer.JoinResponce
	6, // 7: auctioneer.auctioneer.RemovePort:output_type -> auctioneer.RemovePortResponce
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auctioneer_proto_init() }
func file_proto_auctioneer_proto_init() {
	if File_proto_auctioneer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auctioneer_proto_rawDesc), len(file_proto_auctioneer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auctioneer_proto_goTypes,
		DependencyIndexes: file_proto_auctioneer_proto_depIdxs,
		MessageInfos:      file_proto_auctioneer_proto_msgTypes,
	}.Build()
	File_proto_auctioneer_proto = out.File
	file_proto_auctioneer_proto_goTypes = nil
	file_proto_auctioneer_proto_depIdxs = nil
}
