// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/auctioneer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auctioneer_SendBid_FullMethodName    = "/auctioneer.auctioneer/SendBid"
	Auctioneer_Results_FullMethodName    = "/auctioneer.auctioneer/Results"
	Auctioneer_JoinMesh_FullMethodName   = "/auctioneer.auctioneer/JoinMesh"
	Auctioneer_RemovePort_FullMethodName = "/auctioneer.auctioneer/RemovePort"
)

// AuctioneerClient is the client API for Auctioneer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctioneerClient interface {
	SendBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponce, error)
	Results(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Outcome, error)
	JoinMesh(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponce, error)
	RemovePort(ctx context.Context, in *RemovePortRequest, opts ...grpc.CallOption) (*RemovePortResponce, error)
}

type auctioneerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctioneerClient(cc grpc.ClientConnInterface) AuctioneerClient {
	return &auctioneerClient{cc}
}

func (c *auctioneerClient) SendBid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidResponce)
	err := c.cc.Invoke(ctx, Auctioneer_SendBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctioneerClient) Results(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Outcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Outcome)
	err := c.cc.Invoke(ctx, Auctioneer_Results_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctioneerClient) JoinMesh(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponce)
	err := c.cc.Invoke(ctx, Auctioneer_JoinMesh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctioneerClient) RemovePort(ctx context.Context, in *RemovePortRequest, opts ...grpc.CallOption) (*RemovePortResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePortResponce)
	err := c.cc.Invoke(ctx, Auctioneer_RemovePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctioneerServer is the server API for Auctioneer service.
// All implementations must embed UnimplementedAuctioneerServer
// for forward compatibility.
type AuctioneerServer interface {
	SendBid(context.Context, *BidRequest) (*BidResponce, error)
	Results(context.Context, *Empty) (*Outcome, error)
	JoinMesh(context.Context, *JoinRequest) (*JoinResponce, error)
	RemovePort(context.Context, *RemovePortRequest) (*RemovePortResponce, error)
	mustEmbedUnimplementedAuctioneerServer()
}

// UnimplementedAuctioneerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctioneerServer struct{}

func (UnimplementedAuctioneerServer) SendBid(context.Context, *BidRequest) (*BidResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBid not implemented")
}
func (UnimplementedAuctioneerServer) Results(context.Context, *Empty) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Results not implemented")
}
func (UnimplementedAuctioneerServer) JoinMesh(context.Context, *JoinRequest) (*JoinResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinMesh not implemented")
}
func (UnimplementedAuctioneerServer) RemovePort(context.Context, *RemovePortRequest) (*RemovePortResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePort not implemented")
}
func (UnimplementedAuctioneerServer) mustEmbedUnimplementedAuctioneerServer() {}
func (UnimplementedAuctioneerServer) testEmbeddedByValue()                    {}

// UnsafeAuctioneerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctioneerServer will
// result in compilation errors.
type UnsafeAuctioneerServer interface {
	mustEmbedUnimplementedAuctioneerServer()
}

func RegisterAuctioneerServer(s grpc.ServiceRegistrar, srv AuctioneerServer) {
	// If the following call pancis, it indicates UnimplementedAuctioneerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auctioneer_ServiceDesc, srv)
}

func _Auctioneer_SendBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctioneerServer).SendBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auctioneer_SendBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctioneerServer).SendBid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auctioneer_Results_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctioneerServer).Results(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auctioneer_Results_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctioneerServer).Results(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auctioneer_JoinMesh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctioneerServer).JoinMesh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auctioneer_JoinMesh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctioneerServer).JoinMesh(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auctioneer_RemovePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctioneerServer).RemovePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auctioneer_RemovePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctioneerServer).RemovePort(ctx, req.(*RemovePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auctioneer_ServiceDesc is the grpc.ServiceDesc for Auctioneer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auctioneer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auctioneer.auctioneer",
	HandlerType: (*AuctioneerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBid",
			Handler:    _Auctioneer_SendBid_Handler,
		},
		{
			MethodName: "Results",
			Handler:    _Auctioneer_Results_Handler,
		},
		{
			MethodName: "JoinMesh",
			Handler:    _Auctioneer_JoinMesh_Handler,
		},
		{
			MethodName: "RemovePort",
			Handler:    _Auctioneer_RemovePort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auctioneer.proto",
}
